name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: pwsh
    working-directory: './src/WebClient'

env:
    NODEJS_VERSION: '22.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODEJS_VERSION }}
        cache: npm
        cache-dependency-path: ./src/WebClient/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Verify formatting
      run: npm run lint:check

    - name: Build sources
      run: npm run build
    